quote path in CxxFlags
RcppCore/Rcpp pull request #1189
Opened 2021-11-11 18:23 UTC by kevinushey

### Pull Request Template for Rcpp

Closes https://github.com/RcppCore/Rcpp/issues/1188.

#### Checklist

- [x] Code compiles correctly
- [x] `R CMD check` still passes all tests
- [ ] Preferably, new tests were added which fail without the change
- [x] Document the changes by file in [ChangeLog](https://github.com/RcppCore/Rcpp/blob/master/ChangeLog)

2021-11-11 18:25 UTC, eddelbuettel requested changes

2021-11-11 18:25 UTC, eddelbuettel commented on R/RcppLdpath.R
> +    paste0(
Can you make that line, please, to remain consistent with the rest of the code of the package?

2021-11-11 18:25 UTC, eddelbuettel commented on R/RcppLdpath.R
> +        if (cxx0x && canUseCXX0X()) ' -std=c++0x' else ''
Shall we prune this while we're add it?  R's minimum these days is C++11, and will soon be C++14.

2021-11-14 23:40 UTC, eddelbuettel commented on R/RcppLdpath.R
> +    paste0(
Updated / simplified.

2021-11-14 23:41 UTC, eddelbuettel commented on R/RcppLdpath.R
> +        if (cxx0x && canUseCXX0X()) ' -std=c++0x' else ''
Ditto.

2021-11-15 23:34 UTC, eddelbuettel approved these changes

2021-11-15 23:35 UTC, eddelbuettel commented
It's a wee bit circular but I just approved the changes I made ... after requesting them first :)   Will let it sit for a bit and merge if nobody complains...

2021-11-16 00:00 UTC, kevinushey commented
Thanks! I approve of your changes as well, not that you needed it here. :-)

2021-11-16 00:01 UTC, merged

2023-03-17 15:32 UTC, stefanoborini commented
Is it possible that this change has compromised building on macOS monterey and R 4.0.1? I am seeing a failure on 1.0.10 that was not occurring on 1.0.7:

```
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  `/Library/Frameworks/R.framework/Resources/bin/Rscript -e "Rcpp:::CxxFlags()"` -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -c src/myfile.cc -o myfile.o
Using environment default (R version: 4.0.4, platform: x86_64-apple-darwin17.0)
src/myfile.cc:2:10: fatal error: 'Rcpp.h' file not found
#include <Rcpp.h>
         ^~~~~~~~
```

The content of src/Makevars is as follows:

```
## Use the R_HOME indirection to support installations of multiple R version
PKG_LIBS = `$(R_HOME)/bin/Rscript -e "Rcpp:::LdFlags()"`
PKG_CXXFLAGS=`$(R_HOME)/bin/Rscript -e "Rcpp:::CxxFlags()"`
```

I am unsure if this is due to the addition of the quotes, but it seems so. In 1.0.7 I obtained:

```
$ clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  `/Library/Frameworks/R.framework/Resources/bin/Rscript -e "Rcpp:::CxxFlags()"` -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -c src/myfile.cc -o myfile.o
Using environment default (R version: 4.0.4, platform: x86_64-apple-darwin17.0)
In file included from src/myfile.cc:2:
In file included from <redacted>/.envs/default/lib/Rcpp/include/Rcpp.h:27:
In file included from <redacted>/.envs/default/lib/Rcpp/include/RcppCommon.h:167:
<redacted>/.envs/default/lib/Rcpp/include/Rcpp/internal/r_coerce.h:255:7: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]

<compilation continues and finishes>
```

2023-03-17 15:38 UTC, eddelbuettel commented
Why do you use `Rscript -e "Rcpp:::CxxFlags()"` which was deprecated around a decade ago?  If you do non-standard things, and it breaks, you get to keep the pieces.  Maybe try a quick `Rcpp.package.skeleton("newpackage")` and compare the basic setup to what you use, you are likely better off using what everybody else is using as it is more tested.

2023-03-17 15:49 UTC, eddelbuettel commented
You appear to want to have it both ways:  Use _your code_ from ten years ago unchanged, yet rely an brand-new code?  Is see a disconnect here.   _Many_ packages among the 2600+ on CRAN that use Rcpp also started a long time ago, yet managed to update their processes.

In any event, we (and CRAN) test rigourously, and I think most people find that playing with (rather than against) that setup works for them.  If you manage to isolate a breakage, please try to reproduce it in a minimal setup on current versions.

2023-03-17 15:52 UTC, stefanoborini commented
I don't deploy on CRAN. All I know is that I get dumped a 10 years old package on my lap and have to make it work, and all I know is that with 1.0.7 of Rcpp it worked and with a patchlevel version bump it doesn't.